{
    'name': 'Estate',
    'version': '1.9',
    'category': 'Real Estate/Estate',
    'summary': 'A real estate advertisement module',
    'license': 'LGPL-3',
    'Author': 'Cayleb Mutua',
    'installable': True,
    'application':True,
    'depends': ['base' ,'mail' ],
    'data': ['demo/demo.xml',
             'security/res_groups.xml',
             'security/ir.model.access.csv',
             'views/estate_menu.xml',
             'views/estate_settings_menu.xml',
             'views/property_type_menu.xml',
             'views/estate_property_views.xml',
             "views/estate_property_type_views.xml",
             "views/estate_property_offers_views.xml",
             "views/estate_property_tags_views.xml",
             "views/property_tag_menu.xml",
             "views/property_offers_menu.xml",
             'views/res_users_views.xml',
             
            ],
   
}
